### ISSUE TITLE
Error when when using provided checkpiont

### ISSUE THREAD

**Issue by doktorsleepelss** [YassineYousfi/comma10k-baseline#3]
I get   "AssertionError: Images not found" when using the provided checkpoint (epoch.28_val_loss.0.0439.ckpt) to predict masks.  Works fine when I I use my own checkpoint.   I'm using pytorch 1.7.

**Comment by YassineYousfi** [comment]
Should work now when you give --data-path to predict_folder.py (the data-path you used for training, it won't be used, just for a check the model performs automatically)

**Comment by doktorsleepelss** [comment]
> Should work now when you give --data-path to predict_folder.py (the data-path you used for training, it won't be used, just for a check the model performs automatically)

Is this what you mean? Maybe I'm misunderstanding you.

python predict_folder.py --batch-size 20 --folder-to-predict /home/doktor/Desktop/comma10k-baseline --resume-from-checkpoint /home/doktor/Downloads/epoch.28_val_loss.0.0439.ckpt --data-path /home/doktor/Desktop/comma10k-baseline

Still not working.

**Comment by doktorsleepelss** [comment]
All good now. Had the wrong path for --data-path. Changed in to the comma10k folder where I have my data.
